export const ActionTypes = {
    FETCH_NEWS: 'FETCH_NEWS',
    FETCH_NEWS_COMPLETE: 'FETCH_NEWS_COMPLETE',
    FETCH_NEWS_ERROR: 'FETCH_NEWS_ERROR',
    FETCH_ALL_COINS: 'FETCH_ALL_COINS',
    FETCH_ALL_COINS_COMPLETE: 'FETCH_ALL_COINS_COMPLETE',
    FETCH_ALL_COINS_ERROR: 'FETCH_ALL_COINS_ERROR',
    FETCH_GLOBAL_METRICS: 'FETCH_GLOBAL_METRICS',
    FETCH_GLOBAL_METRICS_COMPLETE: 'FETCH_GLOBAL_METRICS_COMPLETE',
    FETCH_GLOBAL_METRICS_ERROR: 'FETCH_GLOBAL_METRICS_ERROR',
};
